/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testhsql.sales;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * ActionItem generated by hbm2java
 */
@Entity
@Table(name="`action_item`"
)

public class ActionItem  implements java.io.Serializable {

    
    private Integer id;
    
    private Date createdDate;
    
    private Date dueDate;
    
    private String proposalStatus;
    
    private String actionStatus;
    
    private String description;
    
    private String owner;
    
    private String assignedTo;

    public ActionItem() {
    }


    @Id @GeneratedValue(strategy=IDENTITY)
    

    @Column(name="`id`", precision=10)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)

    @Column(name="`created_date`", length=10)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Temporal(TemporalType.DATE)

    @Column(name="`due_date`", length=10)
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    

    @Column(name="`proposal_status`", length=45)
    public String getProposalStatus() {
        return this.proposalStatus;
    }
    
    public void setProposalStatus(String proposalStatus) {
        this.proposalStatus = proposalStatus;
    }

    

    @Column(name="`action_status`", length=45)
    public String getActionStatus() {
        return this.actionStatus;
    }
    
    public void setActionStatus(String actionStatus) {
        this.actionStatus = actionStatus;
    }

    

    @Column(name="`description`", length=200)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    

    @Column(name="`owner`", length=100)
    public String getOwner() {
        return this.owner;
    }
    
    public void setOwner(String owner) {
        this.owner = owner;
    }

    

    @Column(name="`assigned_to`", length=100)
    public String getAssignedTo() {
        return this.assignedTo;
    }
    
    public void setAssignedTo(String assignedTo) {
        this.assignedTo = assignedTo;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof ActionItem) )
		    return false;

		 ActionItem that = (ActionItem) o;

		 return ( (this.getId()==that.getId()) || ( this.getId()!=null && that.getId()!=null && this.getId().equals(that.getId()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );

         return result;
    }


}

