/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testhsql.sales;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * Sale generated by hbm2java
 */
@Entity
@Table(name="`sale`"
)

public class Sale  implements java.io.Serializable {

    
    private Integer id;
    
    private Integer year;
    
    private Integer quarter;
    
    private Date date;
    
    private String client;
    
    private String accountManager;
    
    private Float revenue;
    
    private String product;

    public Sale() {
    }


    @Id @GeneratedValue(strategy=IDENTITY)
    

    @Column(name="`id`", precision=10)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    

    @Column(name="`year`", precision=10)
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }

    

    @Column(name="`quarter`", precision=10)
    public Integer getQuarter() {
        return this.quarter;
    }
    
    public void setQuarter(Integer quarter) {
        this.quarter = quarter;
    }

    @Temporal(TemporalType.DATE)

    @Column(name="`date`", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    

    @Column(name="`client`", length=100)
    public String getClient() {
        return this.client;
    }
    
    public void setClient(String client) {
        this.client = client;
    }

    

    @Column(name="`accountManager`", length=100)
    public String getAccountManager() {
        return this.accountManager;
    }
    
    public void setAccountManager(String accountManager) {
        this.accountManager = accountManager;
    }

    

    @Column(name="`revenue`", precision=10)
    public Float getRevenue() {
        return this.revenue;
    }
    
    public void setRevenue(Float revenue) {
        this.revenue = revenue;
    }

    

    @Column(name="`product`", length=30)
    public String getProduct() {
        return this.product;
    }
    
    public void setProduct(String product) {
        this.product = product;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof Sale) )
		    return false;

		 Sale that = (Sale) o;

		 return ( (this.getId()==that.getId()) || ( this.getId()!=null && that.getId()!=null && this.getId().equals(that.getId()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );

         return result;
    }


}

